### ISSUE TITLE
server timeout when sending emails

### ISSUE THREAD

**Issue by nilesjohnson** [nilesjohnson/conference-list#77]
I don't know if this is a server problem or a problem with the email function.  Here is the error log

```
2021-06-15 13:56:56 Error: [SocketException] Connection timed out
Request URL: /conferences/add
Stack Trace:
#0 /home/nilesjohnson/cakephp/lib/Cake/Network/Email/SmtpTransport.php(146): CakeSocket->connect()
#1 /home/nilesjohnson/cakephp/lib/Cake/Network/Email/SmtpTransport.php(86): SmtpTransport->_connect()
#2 /home/nilesjohnson/cakephp/lib/Cake/Network/Email/CakeEmail.php(1183): SmtpTransport->send(Object(CakeEmail))
#3 /home/nilesjohnson/WEBSITES/mathmeetings.net/Controller/ConferencesController.php(449): CakeEmail->send()
#4 /home/nilesjohnson/WEBSITES/mathmeetings.net/Controller/ConferencesController.php(401): ConferencesController->save_and_send()
#5 [internal function]: ConferencesController->add()
#6 /home/nilesjohnson/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(ConferencesController), Array)
#7 /home/nilesjohnson/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#8 /home/nilesjohnson/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ConferencesController), Object(CakeRequest))
#9 /home/nilesjohnson/WEBSITES/mathmeetings.net/webroot/index.php(131): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}

```

**Comment by nilesjohnson** [comment]
fixed in
 - 66e247cde325a0a6fdcaf274d873b32b037fccca
 - 7a426cca92d23b619d78d156bc512519f952c36a
 - 1bdf6a4ce708fe507f8ebe87391d76824d265d2c
