### ISSUE TITLE
error with accent characters in title

### ISSUE THREAD

**Issue by nilesjohnson** [nilesjohnson/conference-list#78]
Accented characters in titles are causing server errors.  For example, a conference with the title

test 2 update üáèŭ accents

causes the following server error.  This is unrelated to the email timeout in #77, because the send email line was disabled for this test.

```
2021-06-15 14:09:49 Error: [PDOException] SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xC5\xAD acc...' for column 'title' at row 1
Request URL: /conferences/edit/1090/4cVm5uT8
Stack Trace:
#0 /home/nilesjohnson/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /home/nilesjohnson/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('UPDATE `nilesjo...', Array)
#2 /home/nilesjohnson/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(425): DboSource->execute('UPDATE `nilesjo...')
#3 /home/nilesjohnson/cakephp/lib/Cake/Model/Model.php(1926): Mysql->update(Object(Conference), '`id` = 1090, `e...', Array)
#4 /home/nilesjohnson/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#5 /home/nilesjohnson/WEBSITES/mathmeetings.net/Controller/ConferencesController.php(439): Model->save(Array)
#6 /home/nilesjohnson/WEBSITES/mathmeetings.net/Controller/ConferencesController.php(536): ConferencesController->save_and_send()
#7 [internal function]: ConferencesController->edit('1090', '4cVm5uT8')
#8 /home/nilesjohnson/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(ConferencesController), Array)
#9 /home/nilesjohnson/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 /home/nilesjohnson/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ConferencesController), Object(CakeRequest))
#11 /home/nilesjohnson/WEBSITES/mathmeetings.net/webroot/index.php(131): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2021-06-15 14:10:03 Error: [PDOException] SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xC5\xAD acc...' for column 'title' at row 1
Request URL: /conferences/edit/1090/4cVm5uT8
Stack Trace:
#0 /home/nilesjohnson/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /home/nilesjohnson/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('UPDATE `nilesjo...', Array)
#2 /home/nilesjohnson/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(425): DboSource->execute('UPDATE `nilesjo...')
#3 /home/nilesjohnson/cakephp/lib/Cake/Model/Model.php(1926): Mysql->update(Object(Conference), '`id` = 1090, `e...', Array)
#4 /home/nilesjohnson/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#5 /home/nilesjohnson/WEBSITES/mathmeetings.net/Controller/ConferencesController.php(439): Model->save(Array)
#6 /home/nilesjohnson/WEBSITES/mathmeetings.net/Controller/ConferencesController.php(536): ConferencesController->save_and_send()
#7 [internal function]: ConferencesController->edit('1090', '4cVm5uT8')
#8 /home/nilesjohnson/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(ConferencesController), Array)
#9 /home/nilesjohnson/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 /home/nilesjohnson/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ConferencesController), Object(CakeRequest))
#11 /home/nilesjohnson/WEBSITES/mathmeetings.net/webroot/index.php(131): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
```

**Comment by nilesjohnson** [comment]
update:  this appears to be an issue with the way the characters are entered.  I just tested a title

test ë, ï, é, etc,

by using copy/paste from unicode strings and had no issues.  In my previous test I was using the compose key on my keyboard to enter the accented characters.  So the issue appears to be with _how_ the accented characters are entered.

**Comment by nilesjohnson** [comment]
now that #77 is fixed, I am unable to reproduce this error!

**Comment by nilesjohnson** [comment]
oops; spoke too soon.  A new test installation did not have this issue, but the main site does.  Could be an issue of how encodings are set for the database itself.

Using compose characters, I get the following error message (with debug level 2):

    Error: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xC5\xAD acc...' for column 'title' at row 1

```
SQL Query: UPDATE `nilesjoh_mathmeetings_PRODUCTION`.`conferences` SET `id` = 1110, `edit_key` = 'Evk3Wrnp', `title` = 'test áççënts üáèŭ accents', `start_date` = '2019-09-05', `end_date` = '2019-09-07', `city` = 'new cité', `country` = 'Jordan', `homepage` = 'http://none.com', `institution` = '', `meeting_type` = 'conference', `contact_name` = '', `contact_email` = 'nilesj@gmail.com', `description` = '<p>another test; </p>\r\n\r\n<p>more accents:</p>\r\n\r\n<p>test áççënts üáèŭ accents</p>' WHERE `nilesjoh_mathmeetings_PRODUCTION`.`conferences`.`id` = '1110' 
```

Note that in the returned sql query, the title contains the accented characters I entered.

**Comment by nilesjohnson** [comment]
further note:  the accented characters also cause an error when they appear in the description, but not the title

```
Error: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xC5\xAD acc...' for column 'description' at row 1
```

```
SQL Query: UPDATE `nilesjoh_mathmeetings_PRODUCTION`.`conferences` SET `id` = 1110, `edit_key` = 'Evk3Wrnp', `title` = 'test accents', `start_date` = '2019-09-05', `end_date` = '2019-09-07', `city` = 'new cité', `country` = 'Jordan', `homepage` = 'http://none.com', `institution` = '', `meeting_type` = 'conference', `contact_name` = '', `contact_email` = 'nilesj@gmail.com', `description` = '<p>another test; </p>\r\n\r\n<p>more accents:</p>\r\n\r\n<p>test üáèŭ accents</p>' WHERE `nilesjoh_mathmeetings_PRODUCTION`.`conferences`.`id` = '1110' 
```

**Comment by nilesjohnson** [comment]
resolved: the database was set to use latin1 encodings, but the data itself was utf8.  Fixed by changing db settings.
